Expose api spec in ingest
swrlab/ard-eventhub pull request #72
Opened 2021-04-25 17:45 UTC by saerdnaer

2021-05-05 10:56 UTC, rafaelmaeuer commented
@saerdnaer could you please explain the intention for exposing api spec source files - what is the benefit of it? I checked out your branch and `/openapi/openapi.json` is now available as link under the title, but `/openapi/openapi.yaml` isn't.

2021-05-05 13:50 UTC, saerdnaer commented
How are you starting the service? For me `/openapi/openapi.yaml` worked... 

Why shouldn't one expose at least the `openapi.json`?

2021-05-07 14:08 UTC, frytg requested changes

2021-05-07 14:29 UTC, frytg approved these changes

2021-05-07 15:10 UTC, merged